-- ============================================================================
-- 0001_init.sql — CPPD Application System initial schema
--
-- This repository is the SINGLE SOURCE OF TRUTH for the database schema.
-- Directus (which runs over the same Postgres) MUST NEVER create or alter
-- these tables. All schema changes happen ONLY via numbered SQL files here.
--
-- Security model (see CLAUDE.md):
--   * RLS is enabled on every table.
--   * Users can SELECT their own applications but can NEVER update or delete
--     them, and can NEVER insert directly.
--   * Application inserts happen ONLY through submit_application()
--     (SECURITY DEFINER).
--   * The storage bucket is PRIVATE; files are served via short-lived signed
--     URLs generated by trusted server code.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------------------
-- Enums
-- ----------------------------------------------------------------------------
do $$ begin
  create type course_level as enum ('foundation', 'diploma', 'advanced');
exception when duplicate_object then null; end $$;

do $$ begin
  create type batch_status as enum ('upcoming', 'open', 'closed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type application_status as enum (
    'submitted', 'under_review', 'accepted', 'rejected', 'withdrawn'
  );
exception when duplicate_object then null; end $$;

-- ----------------------------------------------------------------------------
-- profiles: one row per authenticated user (extends auth.users)
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  full_name     text not null,
  email         text not null,
  phone         text not null,
  cnic          text not null,
  date_of_birth date not null,
  city          text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users manage only their own profile.
create policy "profiles_select_own" on public.profiles
  for select to authenticated using (auth.uid() = id);

create policy "profiles_insert_own" on public.profiles
  for insert to authenticated with check (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
  for update to authenticated
  using (auth.uid() = id) with check (auth.uid() = id);

-- ----------------------------------------------------------------------------
-- courses
-- ----------------------------------------------------------------------------
create table if not exists public.courses (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique,
  title           text not null,
  summary         text not null,
  level           course_level not null,
  duration_months int not null check (duration_months > 0),
  is_published    boolean not null default false,
  created_at      timestamptz not null default now()
);

alter table public.courses enable row level security;

-- Anyone (incl. anonymous visitors) may read PUBLISHED courses only.
create policy "courses_select_published" on public.courses
  for select to anon, authenticated using (is_published);

-- ----------------------------------------------------------------------------
-- batches: intakes for a course
-- ----------------------------------------------------------------------------
create table if not exists public.batches (
  id                   uuid primary key default gen_random_uuid(),
  course_id            uuid not null references public.courses (id) on delete cascade,
  name                 text not null,
  status               batch_status not null default 'upcoming',
  start_date           date not null,
  application_deadline date not null,
  seats                int not null check (seats >= 0),
  created_at           timestamptz not null default now()
);

create index if not exists batches_course_id_idx on public.batches (course_id);

alter table public.batches enable row level security;

-- Anyone may read batches that belong to a published course.
create policy "batches_select_public" on public.batches
  for select to anon, authenticated using (
    exists (
      select 1 from public.courses c
      where c.id = batches.course_id and c.is_published
    )
  );

-- ----------------------------------------------------------------------------
-- applications: APPEND-ONLY for users
-- ----------------------------------------------------------------------------
create table if not exists public.applications (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users (id) on delete cascade,
  batch_id              uuid not null references public.batches (id) on delete restrict,
  highest_qualification text not null,
  motivation            text not null,
  cnic_document_path    text,
  status                application_status not null default 'submitted',
  created_at            timestamptz not null default now(),
  unique (user_id, batch_id)
);

create index if not exists applications_user_id_idx on public.applications (user_id);
create index if not exists applications_batch_id_idx on public.applications (batch_id);

alter table public.applications enable row level security;

-- Users may READ their own applications. There are intentionally NO insert,
-- update, or delete policies for users: inserts go through submit_application()
-- (SECURITY DEFINER), and applications are immutable to users.
create policy "applications_select_own" on public.applications
  for select to authenticated using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- submit_application(): the ONLY path for creating an application.
-- SECURITY DEFINER so it can insert despite the table having no user insert
-- policy. Validates the caller and the batch before writing.
-- ----------------------------------------------------------------------------
create or replace function public.submit_application(
  p_batch_id              uuid,
  p_highest_qualification text,
  p_motivation            text,
  p_cnic_document_path    text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_app_id  uuid;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  -- The batch must exist and be open for applications.
  if not exists (
    select 1 from public.batches b
    where b.id = p_batch_id
      and b.status = 'open'
      and b.application_deadline >= current_date
  ) then
    raise exception 'This batch is not open for applications';
  end if;

  -- A profile must exist for the applicant.
  if not exists (select 1 from public.profiles p where p.id = v_user_id) then
    raise exception 'Complete your profile before applying';
  end if;

  insert into public.applications (
    user_id, batch_id, highest_qualification, motivation, cnic_document_path
  )
  values (
    v_user_id, p_batch_id, p_highest_qualification, p_motivation,
    p_cnic_document_path
  )
  returning id into v_app_id;

  return v_app_id;
end;
$$;

-- Only authenticated users may call the RPC (anon cannot).
revoke all on function public.submit_application(uuid, text, text, text) from public;
grant execute on function public.submit_application(uuid, text, text, text)
  to authenticated;

-- ----------------------------------------------------------------------------
-- Storage: PRIVATE bucket for application documents (e.g. CNIC scans).
-- Files are only ever served via short-lived signed URLs.
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('application-documents', 'application-documents', false)
on conflict (id) do nothing;

-- Users may upload into a folder namespaced by their own user id, and read
-- back only their own objects. Everything else is denied by default.
create policy "app_docs_insert_own" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'application-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "app_docs_select_own" on storage.objects
  for select to authenticated using (
    bucket_id = 'application-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
