-- ============================================================================
-- 0001_init.sql — CPPD Application System: extensions & shared helpers
--
-- This repository is the SINGLE SOURCE OF TRUTH for the database schema.
-- Directus (which runs over the same Postgres) MUST NEVER create or alter
-- these tables. All schema changes happen ONLY via numbered SQL files here.
--
-- Migrations are numbered and MUST apply cleanly, in order, to a fresh
-- database:
--   0001_init.sql               extensions + shared trigger helpers
--   0002_profiles.sql           reusable student profile
--   0003_courses.sql            categories, courses, batches, availability
--   0004_applications.sql       applications + files (immutable to users)
--   0005_submit_application.sql the ONLY write path for applications (RPC)
--   0006_seed.sql               reference data (categories + courses)
--   0007_storage.sql            private buckets + storage RLS
--
-- Security model (see CLAUDE.md):
--   * RLS is enabled on every table, default deny.
--   * Users can SELECT their own applications but can NEVER update, delete,
--     or directly insert them.
--   * Application inserts happen ONLY through submit_application()
--     (SECURITY DEFINER, owned by postgres).
--   * All storage buckets are PRIVATE; files are served via short-lived
--     signed URLs generated by trusted server code.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------------------
-- set_updated_at(): generic BEFORE UPDATE trigger that stamps updated_at.
-- Reused by every table that carries an updated_at column.
-- ----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
