-- ============================================================================
-- 0007_storage.sql — private storage buckets + object-level RLS
--
-- Both buckets are PRIVATE. Files are only ever served via short-lived signed
-- URLs generated by trusted server code (never public URLs, never the service
-- key in the client). Per-bucket size (10MB) and mime-type limits are enforced
-- at the bucket level in addition to the RPC's own validation.
--
--   profile-documents   {user_id}/{filename}
--     CNIC front/back + photo. The owner may INSERT/SELECT/UPDATE/DELETE freely
--     BEFORE the file is snapshotted into a submitted application.
--
--   application-uploads {user_id}/{uuid}/{filename}
--     Documents attached to an application. The owner may INSERT and SELECT
--     only. NO UPDATE, NO DELETE: once uploaded, a user cannot remove or swap a
--     file that a submitted application may reference.
--     (TODO: orphaned files from abandoned submissions are cleaned up by a
--      separate admin job — see CLAUDE.md.)
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'profile-documents', 'profile-documents', false, 10485760,
    array['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'application-uploads', 'application-uploads', false, 10485760,
    array['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
  )
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ----------------------------------------------------------------------------
-- profile-documents: full self-service within the owner's folder.
-- ----------------------------------------------------------------------------
drop policy if exists profile_docs_insert_own on storage.objects;
create policy profile_docs_insert_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'profile-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists profile_docs_select_own on storage.objects;
create policy profile_docs_select_own on storage.objects
  for select to authenticated
  using (
    bucket_id = 'profile-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists profile_docs_update_own on storage.objects;
create policy profile_docs_update_own on storage.objects
  for update to authenticated
  using (
    bucket_id = 'profile-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'profile-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists profile_docs_delete_own on storage.objects;
create policy profile_docs_delete_own on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'profile-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ----------------------------------------------------------------------------
-- application-uploads: INSERT + SELECT only, within the owner's folder.
-- Deliberately NO update/delete policies -> attached files are immutable.
-- ----------------------------------------------------------------------------
drop policy if exists app_uploads_insert_own on storage.objects;
create policy app_uploads_insert_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'application-uploads'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists app_uploads_select_own on storage.objects;
create policy app_uploads_select_own on storage.objects
  for select to authenticated
  using (
    bucket_id = 'application-uploads'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
